## Load completion
autoload -U compinit
compinit

setopt completealiases

## Load prompt
autoload -U promptinit
promptinit

autoload -U colors && colors

function color_my_prompt {
    local __user_and_cur_location="%{$fg[yellow]%}${USERNAME} at %~"
    local __git_branch="`git branch 2> /dev/null | grep -e '^*' | sed -E  s/^\\\\\*\ \(.+\)$/\(\\\\\1\)\ /`"
    local __git_stash="$([ ! `git stash list 2> /dev/null | wc -l` -eq '0' ] && echo "(stashed:"`git stash list 2> /dev/null | wc -l | tr -s " "`") ")"
    local __git_branch_color="%{$fg[magenta]%}"
    local __prompt_tail_color="%{$fg[yellow]%}"
    local __prompt_tail="%#: "
    local __last_color="%{$reset_color%}"
    export PROMPT="%{$fg[cyan]%}%(1V.(venv: %1v) .)$__user_and_cur_location $__git_branch_color$__git_branch$__git_stash$__prompt_tail_color$__prompt_tail$__last_color"
}
color_my_prompt

# Redraw the prompt
precmd() {
    color_my_prompt
}

RPROMPT="[ %D %T ]"

export VIRTUAL_ENV_DISABLE_PROMPT=yes

function virtenv_indicator {
if [[ -z $VIRTUAL_ENV ]] then
    psvar[1]=''
else
    psvar[1]=${VIRTUAL_ENV##*/}
fi
}

add-zsh-hook precmd virtenv_indicator


## DIRSTACK

DIRSTACKFILE="$HOME/.cache/zsh/dirs"
if [[ -f $DIRSTACKFILE ]] && [[ $#dirstack -eq 0 ]]; then
    dirstack=( ${(f)"$(< $DIRSTACKFILE)"} )
    [[ -d $dirstack[1] ]] && cd $dirstack[1]
fi
chpwd() {
    print -l $PWD ${(u)dirstack} >$DIRSTACKFILE
}

DIRSTACKSIZE=20

setopt autopushd pushdsilent pushdtohome

## Remove duplicate entries
setopt pushdignoredups

## This reverts the +/- operators.
setopt pushdminus

# SOURCES
# =======

# If exists dir, source custom files where work stuff can be put
# or anything that's custom to some specific environment
PROFILE_CUSTOM_SOURCE_DIR="$HOME/.profile_custom_sources/"
if [ -e $PROFILE_CUSTOM_SOURCE_DIR ]
then
    for f in `ls $PROFILE_CUSTOM_SOURCE_DIR`
    do 
        source $PROFILE_CUSTOM_SOURCE_DIR/$f
    done
else
    mkdir $PROFILE_CUSTOM_SOURCE_DIR
fi

source ~/.bash/fzf # fuzzy commands
source ~/.bash/alias
source ~/.bash/functions
source ~/.bash/path
source ~/.bash/colors

## History
HISTFILE=$HOME/.zhistory       # enable history saving on shell exit
setopt APPEND_HISTORY          # append rather than overwrite history file.
HISTSIZE=1200                  # lines of history to maintain memory
SAVEHIST=1000                  # lines of history to maintain in history file.
setopt HIST_EXPIRE_DUPS_FIRST  # allow dups, but expire old ones when I hit HISTSIZE
setopt EXTENDED_HISTORY        # save timestamp and runtime information
setopt inc_append_history
setopt share_history
setopt HIST_IGNORE_DUPS        # Exclude duplicates from history

cd $HOME
export vps="107.170.138.166"

