#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


# Install Vim
# ===========

ln -s ${BASEDIR}/vim/vimrc ~/.vimrc
ln -s ${BASEDIR}/vim/gvimrc ~/.gvimrc
mkdir ~/.vim

# get Vundle
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
# install plugins
vim +PluginInstall +qall


# Install Git
# ===========

#ln -s ${BASEDIR}/.gitconfig ~/.gitconfig
#echo "Downloading git completion bash..."
#wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
#ln -s ${BASEDIR}/git-completion.bash ~/.git-completion.bash

# ack
cp ${BASEDIR}/ack/ackrc ~/.ackrc


# Install Bash
# ============

ln -s ${BASEDIR}/bash_profile/profile ~/.profile
mkdir ~/.bash
ln -s ${BASEDIR}/bash_profile/fzf ~/.bash/fzf
ln -s ${BASEDIR}/bash_profile/alias ~/.bash/alias
ln -s ${BASEDIR}/bash_profile/functions ~/.bash/functions
ln -s ${BASEDIR}/bash_profile/colors ~/.bash/colors
PROFILE_CUSTOM_SOURCES='~/.profile_custom_sources'
[ -e ${PROFILE_CUSTOM_SOURCES} ] && mkdir ${PROFILE_CUSTOM_SOURCES}
