#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


# Install Vim
# ===========

ln -s ${BASEDIR}/vim/vimrc ~/.vimrc
ln -s ${BASEDIR}/vim/gvimrc ~/.gvimrc
mkdir ~/.vim

# get Vundle
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
# install plugins
vim +PluginInstall +qall


# Install Git
# ===========

echo $BASEDIR
ln -s ${BASEDIR}/git/gitconfig ~/.gitconfig
ln -s ${BASEDIR}/git/git_excludes ~/.git_excludes
echo "Downloading git completion bash..."
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash > ~/.git-completion.bash

# ack
cp ${BASEDIR}/ack/ackrc ~/.ackrc


# Install Bash
# ============

ln -s ${BASEDIR}/bash_profile/profile ~/.profile
ln -s ${BASEDIR}/bash_profile/zshrc ~/.zshrc # zsh stuff
mkdir ~/.bash
ln -s ${BASEDIR}/bash_profile/fzf ~/.bash/fzf
ln -s ${BASEDIR}/bash_profile/alias ~/.bash/alias
ln -s ${BASEDIR}/bash_profile/functions ~/.bash/functions
ln -s ${BASEDIR}/bash_profile/colors ~/.bash/colors
ln -s ${BASEDIR}/bash_profile/path ~/.bash/path
PROFILE_CUSTOM_SOURCES='~/.profile_custom_sources'
[ -e ${PROFILE_CUSTOM_SOURCES} ] && mkdir ${PROFILE_CUSTOM_SOURCES}
