#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Install Vim
# ===========

cp ${BASEDIR}/vim/vimrc ~/.vimrc
cp ${BASEDIR}/vim/gvimrc ~/.gvimrc
mkdir ~/.vim

# get Vundle
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
# install plugins
vim +PluginInstall +qall

# Install Git
# ===========

#ln -s ${BASEDIR}/.gitconfig ~/.gitconfig
#echo "Downloading git completion bash..."
#wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
#ln -s ${BASEDIR}/git-completion.bash ~/.git-completion.bash

# ack
cp ${BASEDIR}/ackrc ~/.ackrc
