" VUNDLE CONFIGURATION
" ====================

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'mileszs/ack.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'klen/python-mode'
Plugin 'bling/vim-airline'
Plugin 'altercation/vim-colors-solarized'
Plugin 'airblade/vim-gitgutter'
Plugin 'msanders/snipmate.vim'

call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"
" END OF VUNDLE CONFIGURATION


" MY OWN CONFIGURATION
" ====================

set ts=4
set expandtab
set shiftwidth=4
set guifont=Monaco:h13 
set enc=utf-8
set nu
set si
set backspace=2
set hid
set foldmethod=syntax
set nowrap
set autoread
set laststatus=2
set showmatch
set nosmartindent " messes with python comments: (http://stackoverflow.com/questions/354097/how-to-configure-vim-to-not-put-comments-at-the-beginning-of-lines-while-editing)
set cursorline
set scrolloff=999 " keep cursor centered when scrolling

noremap <C-Tab> :bn<Enter>
noremap <C-b> :CtrlPBuffer<Enter>
noremap <leader>n :NERDTreeToggle<CR>
nnoremap <leader>a <Esc>:Ack!
" Use ack to search for word under cursor
noremap <leader>w "ayiw<Esc>:Ack!<C-r>a<cr>
" Edit vimrc
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
" Source vimrc
nnoremap <leader>sv :source $MYVIMRC<cr>
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l
nmap <C-h> <C-w>h
nnoremap <leader>6 <C-^>

:syntax enable
:filetype indent on

syntax on

" If you prefer the Omni-Completion tip window to close when a selection is
" " made, these lines close it on movement in insert mode or when leaving
" " insert mode
augroup omnicompletion
    autocmd!
    autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
    autocmd InsertLeave * if pumvisible() == 0|pclose|endif
augroup END 

" Fugitive shortcuts
nnoremap <leader>gb :Gblame<cr>
nnoremap <leader>gd :Gdiff<cr>
nnoremap <leader>gs :Gstatus<cr>

" Otherwise in MacOSX git commit can fail:
" https://github.com/bling/vim-airline/issues/79
let g:airline_theme='dark'
let g:airline#extensions#branch#enabled=1

let g:solarized_termcolors = 256  "
colorscheme solarized
set background=dark

" Open go to definition in vertical split
let g:pymode_rope_goto_definition_cmd='vnew'
