" VUNDLE CONFIGURATION
" ====================

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'mileszs/ack.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'klen/python-mode'
Plugin 'bling/vim-airline'
Plugin 'altercation/vim-colors-solarized'
Plugin 'airblade/vim-gitgutter'
Plugin 'msanders/snipmate.vim'
Plugin 'moll/vim-bbye'
Plugin 'notpratheek/vim-luna'
Plugin 'surround.vim'
Plugin 'davidhalter/jedi-vim'
Plugin 'L9'
Plugin 'FuzzyFinder'
Plugin 'pangloss/vim-javascript'
Plugin 'scrooloose/syntastic'
Plugin 'leafgarland/typescript-vim'
Plugin 'Quramy/tsuquyomi'
Plugin 'Shougo/vimproc.vim'
Plugin 'geekjuice/vim-mocha'
Plugin 'joonty/vdebug'

call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"
" END OF VUNDLE CONFIGURATION


" MY OWN CONFIGURATION
" ====================

set ts=4
set expandtab
set shiftwidth=4
set guifont=Monaco:h15
set enc=utf-8
set nu
set si
set backspace=2
set hid
set foldmethod=syntax
set nowrap
set autoread
set laststatus=2
set showmatch
set nosmartindent " messes with python comments: (http://stackoverflow.com/questions/354097/how-to-configure-vim-to-not-put-comments-at-the-beginning-of-lines-while-editing)
set cursorline
set scrolloff=999 " keep cursor centered when scrolling
set guioptions=ac
set exrc
set secure
set tags=.tags/tags
set list
set listchars=trail:…,tab:>-
set colorcolumn=100

noremap <C-Tab> :bn<Enter>
noremap <C-b> :CtrlPBuffer<Enter>
noremap <leader>n :NERDTreeToggle<CR>
nnoremap <leader>a <Esc>:Ack!
" Use ack to search for word under cursor
noremap <leader>w "ayiw<Esc>:Ack!<C-r>a<cr>
" Edit vimrc
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
" Source vimrc
nnoremap <leader>sv :source $MYVIMRC<CR>:source $MYGVIMRC<CR>
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l
nmap <C-h> <C-w>h
nnoremap <leader>6 <C-^>
nnoremap :bd :Bdelete
nnoremap ++ <C-w>\|<C-w>_
nnoremap \|\| <C-w>\|
nnoremap __ <C-w>_
nnoremap == <C-w>=
nnoremap <leader>f :echo @%<CR>
nnoremap <Space><Space> :on<CR>
nnoremap <leader>a :BAwk 
nnoremap <leader>ft :FufTag!<CR>
nnoremap cC c/\u<CR>

:syntax enable
:filetype indent on

syntax on

" If you prefer the Omni-Completion tip window to close when a selection is
" " made, these lines close it on movement in insert mode or when leaving
" " insert mode
augroup omnicompletion
    autocmd!
    autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
    autocmd InsertLeave * if pumvisible() == 0|pclose|endif
augroup END 

" Fugitive shortcuts
nnoremap <leader>gb :Gblame<cr>
nnoremap <leader>gd :Gdiff<cr>
nnoremap <leader>gs :Gstatus<cr>

" Otherwise in MacOSX git commit can fail:
" https://github.com/bling/vim-airline/issues/79
let g:airline_theme='dark'
let g:airline#extensions#branch#enabled=1

let g:solarized_termcolors = 256  "
colorscheme luna-term

" Open go to definition in vertical split
"let g:pymode_rope_goto_definition_cmd='Split'
" Use python-mode mainly for syntax and folding (which is very good)
" Disable for rope and lint
let g:pymode_rope = 0
let g:pymode_lint = 0

" Useful function to split or jump when using rope's go to definition
function! JumpOrSplit( fname )
    let bufnum=bufnr(expand(a:fname))
    let winnum=bufwinnr(bufnum)
    if winnum != -1
        " Jump to existing split
        exe winnum . "wincmd w"
    else
        " Make new split as usual
        exe "vsp " . a:fname
    endif
endfunction

command! -nargs=1 Split :call JumpOrSplit("<args>")

function! BetterAwk(s)
    exe "Ack!\"" . a:s . "\""
endfunction

command! -nargs=1 BAwk :call BetterAwk("<args>")

let g:jedi#call_signatures_command=''
let g:jedi#usages_command=''

" PHP folding
" ===========
let php_folding = 1        "Set PHP folding of classes and functions.
let php_htmlInStrings = 1  "Syntax highlight HTML code inside PHP strings.
let php_sql_query = 1      "Syntax highlight SQL code inside PHP strings.
let php_noShortTags = 1    "Disable PHP short tags.

" Syntastic settings
" ==================
let g:syntastic_typescript_checkers = ['tslint']

